### ISSUE TITLE
Issue running main.py

### ISSUE THREAD

**Issue by FearOfGvd** [Pbatch/ClashRoyaleBuildABot#103]
So I got past every other issue during setup but there is an error code that main.py keeps throwing when I try to run it.

```
Desktop\ClashRoyaleBuildABot-main\example>py main.py
Custom Bot is now running...
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main()
  File "main.py", line 14, in main
    bot.run()
  File "C:\Users\messi\OneDrive\Desktop\ClashRoyaleBuildABot-main\example\custom_bot.py", line 42, in run
    self.set_state()
  File "C:\Users\messi\AppData\Local\Programs\Python\Python38\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 116, in set_state
    self.state = self.detector.run(screenshot)
  File "C:\Users\messi\AppData\Local\Programs\Python\Python38\lib\site-packages\clashroyalebuildabot\state\detector.py", line 63, in run
    self._draw_text(d, v['bounding_box'], str(v['number']))
  File "C:\Users\messi\AppData\Local\Programs\Python\Python38\lib\site-packages\clashroyalebuildabot\state\detector.py", line 35, in _draw_text
    text_width, text_height = self.font.getsize(text)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```

**Comment by Pbatch** [comment]
Try a fresh pip install, I've just updated the package on pypi
