### ISSUE TITLE
Main.py eror:

### ISSUE THREAD

**Issue by mrdarwinjs** [Pbatch/ClashRoyaleBuildABot#104]
Custom Bot is now running...
Traceback (most recent call last):
  File ".\main.py", line 18, in <module>
    main()
  File ".\main.py", line 14, in main
    bot.run()
  File "C:\Users\user\Desktop\ClashRoyaleBuildABot\example\custom_bot.py", line 42, in run
    self.set_state()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 116, in set_state
    self.state = self.detector.run(screenshot)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\clashroyalebuildabot\state\detector.py", line 63, in run
    self._draw_text(d, v['bounding_box'], str(v['number']))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\clashroyalebuildabot\state\detector.py", line 35, in _draw_text
    text_width, text_height = self.font.getsize(text)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**Comment by mrdarwinjs** [comment]
to solve this proglem: pip install Pillow<=9.5.0

**Comment by nschnap** [comment]
> to solve this proglem: pip install Pillow<=9.5.0

this did not work for me. I entered "pip install Pillow<=9.5.0" into the command prompt and it said "The system cannot find the file specified."
