### ISSUE TITLE
Screenshot Problem

### ISSUE THREAD

**Issue by mrpekka12** [Pbatch/ClashRoyaleBuildABot#111]
I was folloiwng the tutorial and when I went to screenshot it gave me a error: 

```
adb.exe:` more than one device/emulator
Traceback (most recent call last):
  File "C:\Users\user\clashroyalebuildabot\screen.py", line 13, in __init__
    window_size = subprocess.check_output(['adb', 'shell', 'wm', 'size'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', 'shell', 'wm', 'size']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\clashroyalebuildabot\screen.py", line 43, in <module>
    main()
  File "C:\Users\user\clashroyalebuildabot\screen.py", line 37, in main
    cls = Screen()
  File "C:\Users\user\clashroyalebuildabot\screen.py", line 15, in __init__
    raise RuntimeError(f"command '{e.cmd}' return with error (code {e.returncode}): {e.output}")
RuntimeError: command '['adb', 'shell', 'wm', 'size']' return with error (code 1): `b''
```

I typed abd, shell, wm, and size into the prompt and it showed me that they weren't recognized besides adb. Idk if this is the issue or not but if it is can someone show me how to install the three?

**Comment by mrpekka12** [comment]
also why does this "emulator-5554" keep auto connecting? I have no idea what that is

**Comment by mrpekka12** [comment]
nvm solved it by myself
