### ISSUE TITLE
No module named 'clashroyalebuildabot'

### ISSUE THREAD

**Issue by KairoARG** [Pbatch/ClashRoyaleBuildABot#147]
C:\Users\athar\ClashRoyaleBuildABot>python example/main.py
Traceback (most recent call last):
  File "C:\Users\athar\ClashRoyaleBuildABot\example\main.py", line 4, in <module>
    import clashroyalebuildabot
ModuleNotFoundError: No module named 'clashroyalebuildabot'

any help? tried everything from changing python version too!

**Comment by Leviaria** [comment]
Please add the `clashroyalebuildabot` folder to your Python path.

🤔 **Need more Help?**
Don’t hesitate to ask any questions on our Discord server. We're here to help!

**Comment by KairoARG** [comment]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\athar\ClashRoyaleBuildABot\example\main.py", line 4, in <module>
    import clashroyalebuildabot
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\__init__.py", line 2, in <module>
    from .bot import PeteBot, RandomBot, StandardBot, TwoSixHogCycle, Action, Bot
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\__init__.py", line 2, in <module>
    from .two_six_hog_cycle import TwoSixHogCycle
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\two_six_hog_cycle\__init__.py", line 2, in <module>
    from .two_six_hog_cycle_bot import TwoSixHogCycle
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\two_six_hog_cycle\two_six_hog_cycle_bot.py", line 7, in <module>
    from clashroyalebuildabot.bot.bot import Bot
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\bot.py", line 21, in <module>
    from clashroyalebuildabot.state.detector import Detector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\__init__.py", line 2, in <module>
    from .detector import Detector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\detector.py", line 9, in <module>
    from clashroyalebuildabot.state.number_detector import NumberDetector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\number_detector.py", line 11, in <module>
    from clashroyalebuildabot.state.onnx_detector import OnnxDetector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\onnx_detector.py", line 2, in <module>
    import onnxruntime
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "C:\Users\athar\ClashRoyaleBuildABot\example\main.py", line 4, in <module>
    import clashroyalebuildabot
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\__init__.py", line 2, in <module>
    from .bot import PeteBot, RandomBot, StandardBot, TwoSixHogCycle, Action, Bot
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\__init__.py", line 2, in <module>
    from .two_six_hog_cycle import TwoSixHogCycle
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\two_six_hog_cycle\__init__.py", line 2, in <module>
    from .two_six_hog_cycle_bot import TwoSixHogCycle
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\two_six_hog_cycle\two_six_hog_cycle_bot.py", line 7, in <module>
    from clashroyalebuildabot.bot.bot import Bot
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\bot\bot.py", line 21, in <module>
    from clashroyalebuildabot.state.detector import Detector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\__init__.py", line 2, in <module>
    from .detector import Detector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\detector.py", line 9, in <module>
    from clashroyalebuildabot.state.number_detector import NumberDetector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\number_detector.py", line 11, in <module>
    from clashroyalebuildabot.state.onnx_detector import OnnxDetector
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\clashroyalebuildabot\state\onnx_detector.py", line 2, in <module>
    import onnxruntime
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\athar\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError

**Comment by Leviaria** [comment]
pip uninstall numpy onnxruntime onnxruntime-gpu Pillow protobuf scipy rich loguru adb-shell PyYAML pybind11

&

pip install flatbuffers>=2.0 numpy>=1.23.5,!=2.0.0,!=2.0.1 onnxruntime onnxruntime-gpu>=1.18.0 Pillow>=10.1.0 protobuf>=3.20.3 scipy>=1.13.1 rich>=13.7.1 loguru>=0.7.2 adb-shell[async]==0.4.4 PyYAML pybind11>=2.12
