### ISSUE TITLE
[Bug] Script wont stop

### ISSUE THREAD

**Issue by DESTROYER-32** [Pbatch/ClashRoyaleBuildABot#201]
Usually when sending  stop (Ctrl + c) signal the bot should stop but instead it throws 

`Traceback (most recent call last):
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\clashroyalebuildabot\bot\bot.py", line 198, in run
    self.step()
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\clashroyalebuildabot\bot\bot.py", line 172, in step
    time.sleep(1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\main.py", line 48, in <module>
    main()
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\main.py", line 42, in main
    bot.run()
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\clashroyalebuildabot\bot\bot.py", line 200, in run
    self.emulator.quit()
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\clashroyalebuildabot\emulator\emulator.py", line 150, in quit
    self.screenshot_thread.kill()
  File "C:\Users\XYZ\Git\ClashRoyaleBuildABot\clashroyalebuildabot\emulator\emulator.py", line 39, in kill
    def kill(self):
KeyboardInterrupt`

and I have to kil the terminal and then restart it again.

**Comment by Leviaria** [comment]
You can now kill it with CTRL + X
