### ISSUE TITLE
getting these errors

### ISSUE THREAD

**Issue by helioseu** [Pbatch/ClashRoyaleBuildABot#27]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 8, in main
    bot.run()
  File "C:\Users\helios\Downloads\kj\ClashRoyaleBuildABot\src\bot\standard\standard_bot.py", line 35, in run
    self.set_state()
  File "C:\Users\helios\Downloads\kj\ClashRoyaleBuildABot\src\bot\bot.py", line 101, in set_state
    screenshot = self.screen.take_screenshot()
  File "C:\Users\helios\Downloads\kj\ClashRoyaleBuildABot\src\screen.py", line 19, in take_screenshot
    screenshot = self.device.screencap()
AttributeError: 'NoneType' object has no attribute 'screencap'

**Comment by Pbatch** [comment]
The device has not been set, probably because the Python script cannot see the BlueStacks emulator. Have you installed ADB? If so, have you started the ADB server? If so, have you turned on the Android debug bridge in the BlueStacks settings? Ref - https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/Setup

If it's still not working, see if you can find BlueStacks among the listed devices using ppadb. https://pypi.org/project/pure-python-adb/

Let me know if any of these links help, or if any other errors pop up :)
