### ISSUE TITLE
about running bot

### ISSUE THREAD

**Issue by vyscoz** [Pbatch/ClashRoyaleBuildABot#37]
im new here, how im running this bot?im try running main.py and nothing happened, someone can help?

**Comment by marmig0404** [comment]
The package for this library must be installed with `pip install ClashRoyaleBuildABot`.
Then the package can be imported like in **`examples/`**. To run the test file, run `python main.py`.

Offical documentation for this will be available soon.

**Comment by marmig0404** [comment]
The official documentation for the setup is available [in the wiki](https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/Setup).

**Comment by vyscoz** [comment]
after install package with pip install ClashRoyaleBuildABot, so where i can find example file?

**Comment by marmig0404** [comment]
You can download the raw copies of the example files linked above or you can clone the repository with `git clone https://github.com/Pbatch/ClashRoyaleBuildABot` and locate the **`example/`** directory.

These files show an example implementation of this library using imports in python.

**Comment by vyscoz** [comment]
still cant running

**Comment by marmig0404** [comment]
can you share the commands you ran and their output to the console?

**Comment by vyscoz** [comment]
C:\CRBot\ClashRoyaleBuildABot-main\clashroyalebuildabot\bot\standard>main.py
Traceback (most recent call last):
  File "C:\CRBot\ClashRoyaleBuildABot-main\clashroyalebuildabot\bot\standard\main.py", line 14, in <module>
    main()
  File "C:\CRBot\ClashRoyaleBuildABot-main\clashroyalebuildabot\bot\standard\main.py", line 8, in main
    bot = StandardBot(card_names, debug=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\bot\standard\standard_bot.py", line 14, in __init__
    super().__init__(card_names, StandardAction, debug=debug)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 35, in __init__
    self.detector = Detector(card_names, debug=self.debug)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\detector.py", line 25, in __init__
    self.card_detector = CardDetector(self.card_names)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\card_detector.py", line 15, in __init__
    self.cards, self.card_hashes = self._calculate_cards_and_card_hashes()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\card_detector.py", line 50, in _calculate_cards_and_card_hashes
    with open(f'{DATA_DIR}/cards.csv') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\clashroyalebuildabot\\data/cards.csv'

**Comment by gl4d** [comment]
yeah getting the same error:

`C:\Users\XX\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example>.\main.py
Traceback (most recent call last):
  File "C:\Users\XX\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 18, in <module>
    main()
  File "C:\Users\XX\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 12, in main
    bot = CustomBot(card_names, debug=True)
  File "C:\Users\XX\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\custom_bot.py", line 19, in __init__
    super().__init__(card_names, CustomAction, debug=debug)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 35, in __init__
    self.detector = Detector(card_names, debug=self.debug)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\detector.py", line 25, in __init__
    self.card_detector = CardDetector(self.card_names)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\card_detector.py", line 15, in __init__
    self.cards, self.card_hashes = self._calculate_cards_and_card_hashes()
  File "C:\Users\XX\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\card_detector.py", line 50, in _calculate_cards_and_card_hashes
    with open(f'{DATA_DIR}/cards.csv') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XX\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\clashroyalebuildabot\\data/cards.csv'`

related to the last update of clash i guess?

**Comment by marmig0404** [comment]
This is a packaging error, I'll be opening a PR to fix this later today.

**Comment by marmig0404** [comment]
should be all fixed, try a reinstall with `pip --force-reinstall --no-cache-dir ClashRoyaleBuildABot==1.01`

**Comment by gl4d** [comment]
> pip --force-reinstall --no-cache-dir ClashRoyaleBuildABot==1.0.1

gives ### **no such option: --force-reinstall**
downloaded the latest release "Import hotfix" and did a fresh ### **python setup.py install**

still giving the same error.

**Comment by marmig0404** [comment]
I made an edit to the command above, needed to specify the initial `pip install`

As for install with setup.py, run `pip install -e setup.py`

**Comment by gl4d** [comment]
did: pip install --force-reinstall --no-cache-dir ClashRoyaleBuildABot==1.0.1
installed everything perfectly fine.
then did: 
> python main.py

diff error this time:
> python main.py
> Traceback (most recent call last):
>   File "C:\Users\SP\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 18, in <module>
>     main()
>   File "C:\Users\SP\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 14, in main
>     bot.run()
>   File "C:\Users\SP\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\custom_bot.py", line 40, in run
>     self.set_state()
>   File "C:\Users\SP\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 101, in set_state
>     screenshot = self.screen.take_screenshot()
>   File "C:\Users\SP\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\screen.py", line 19, in take_screenshot
>     screenshot = self.device.screencap()
> AttributeError: 'NoneType' object has no attribute 'screencap'

**Comment by marmig0404** [comment]
Since the install checks out, I'm moving this to a new issue #39
