### ISSUE TITLE
Issue running main.py

### ISSUE THREAD

**Issue by rafaelebert** [Pbatch/ClashRoyaleBuildABot#50]
Hello all... I've been getting this error when running the main.py example

Traceback (most recent call last):
  File "c:\platform-tools\ClashRoyaleBuildABot\example\main.py", line 18, in <module>
    main()
  File "c:\platform-tools\ClashRoyaleBuildABot\example\main.py", line 14, in main
    bot.run()
  File "c:\platform-tools\ClashRoyaleBuildABot\example\custom_bot.py", line 41, in run
    self.set_state()
  File "C:\Users\Ebert\AppData\Local\Programs\Python\Python310\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 101, in set_state
    screenshot = self.screen.take_screenshot()
  File "C:\Users\Ebert\AppData\Local\Programs\Python\Python310\lib\site-packages\clashroyalebuildabot\screen.py", line 19, in take_screenshot
    screenshot = self.device.screencap()
AttributeError: 'NoneType' object has no attribute 'screencap'

Any ideas on what can be causing it?

**Comment by rafaelebert** [comment]
closing this as seen there is another post about this... thanks and sorry for the duplicate.
