### ISSUE TITLE
Bot is unable to take screencaps

### ISSUE THREAD

**Issue by hexiro** [Pbatch/ClashRoyaleBuildABot#53]
Hello, I'm recieving the following traceback when I try and start the bot:
```py
Traceback (most recent call last):
  File "c:\Users\nathanl\Desktop\programming\python\misc\ClashRoyaleBuildABot\example\main.py", line 31, in <module>
    main()
  File "c:\Users\nathanl\Desktop\programming\python\misc\ClashRoyaleBuildABot\example\main.py", line 27, in main
    bot.run()
  File "c:\Users\nathanl\Desktop\programming\python\misc\ClashRoyaleBuildABot\example\custom_bot.py", line 43, in run
    self.set_state()
  File "c:\Users\nathanl\Desktop\programming\python\misc\ClashRoyaleBuildABot\clashroyalebuildabot\bot\bot.py", line 117, in set_state
    screenshot = self.screen.take_screenshot()
  File "c:\Users\nathanl\Desktop\programming\python\misc\ClashRoyaleBuildABot\clashroyalebuildabot\screen.py", line 24, in take_screenshot
    screenshot = self.device.screencap()
AttributeError: 'NoneType' object has no attribute 'screencap'
```

I'm not sure why the device is `None`. I've tried restarting the adb server and changing the port to match Bluestack's port.
Additionally, It appears as though my BlueStacks version uses a pseudorandom port number every time it restarts.

![image](https://user-images.githubusercontent.com/42787085/206209229-c624fb34-59cd-4cd4-be5b-d088f47108ed.png)

Maybe I need to downgrade bluestacks versions? Please let me know if you have any ideas :)

**Comment by Pbatch** [comment]
Hello. I had to reinstall the library the other day and also ran into this issue. 

I've just merged an MR that should fix the problem as I've gotten rid of the "pp-adb" library and just replaced it with shell commands.

There is an extra step in the setup that you now need to follow. (https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/Setup).

After starting the ADB server you must run:
```bash
adb connect 127.0.0.1:<PORT>
```
where `<PORT>` in your example would be `12588`. 

There is no longer a `device` argument to the `Bot` class because of this extra step.

Let me know if this works for you, it seemed to fix things for me :)

**Comment by hexiro** [comment]
It worked! thank you very much for your fast reply, this project is incredible. Do you have any idea how many trophies you can push to before the bot starts to lose trophies? My guess would be 1000-1500 from looking at it so far which is pretty solid.

**Comment by Pbatch** [comment]
I've not tested its limits so I'm not sure. Let us know how far you manage to push it! The biggest barrier at the moment is that as you climb the ranks, the bot can no longer identify the units. I'm going to start some work soon on solving this problem. 

@all-contributors please add @hexiro for submitting a bug report.

**Comment by Pbatch** [comment]
I agree the fireball is annoying. One of the major problems is that ADB takes ~0.5 seconds to take a screenshot, and by then the targets are in a different location. I will have to have another look to see if there is a faster way.

If you come up with better logic for bridge spam / building up a push don't be afraid to shout, the bot is always happy to evolve :)
