### ISSUE TITLE
Help Pls

### ISSUE THREAD

**Issue by JonathanRoiz** [Pbatch/ClashRoyaleBuildABot#81]
I get an error when trying to take the screenshot to test installation.

Console: 
```
C:\Users\jonat\AppData\Local\Programs\Python\Python39\Lib\site-packages>python clashroyalebuildabot/screen.py
adb.exe: more than one device/emulator
Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\Lib\site-packages\clashroyalebuildabot\screen.py", line 41, in <module>
    main()
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\Lib\site-packages\clashroyalebuildabot\screen.py", line 34, in main
    cls = Screen()
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\Lib\site-packages\clashroyalebuildabot\screen.py", line 12, in __init__
    window_size = subprocess.check_output(['adb', 'shell', 'wm', 'size'])
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\jonat\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', 'shell', 'wm', 'size']' returned non-zero exit status 1.
```

**Comment by Pbatch** [comment]
Try running the following to get rid of your old devices/emulators before you start the ADB server.
```
adb kill-server
adb start-server
```

To check that it's working,  ```adb devices``` should only return one device.

If it doesn't, try setting the `ANDROID_SERIAL` environment variable to the serial number of the Bluestacks emulator (returned by the previous command).
