### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by ranger65** [Pbatch/ClashRoyaleBuildABot#86]
Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\65ran>adb start-server

C:\Users\65ran>adb kill-server

C:\Users\65ran>adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

C:\Users\65ran>adb connect 127.0.0.1:5555
connected to 127.0.0.1:5555

C:\Users\65ran>python C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py
error: more than one device and emulator
Traceback (most recent call last):
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 41, in <module>
    main()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 34, in main
    cls = Screen()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 12, in __init__
    window_size = subprocess.check_output(['adb', 'shell', 'wm', 'size'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', 'shell', 'wm', 'size']' returned non-zero exit status 4294967295.

C:\Users\65ran>

**Comment by TheAdroitDBA** [comment]
Try to run 
adb kill-server
then
adb connect 127.0.0.1:5555
adb devices (will list all devices, hopefully only 1)

I believe this happens because when you run adb start-server it automatically connects to the bluestacks instance.

**Comment by ranger65** [comment]
Ran kill server multiple times before I did this and got this ,  after I ran adb devices it said emulator was on 5554 so I tried to connect to it but failed 


Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\65ran>adb kill-server

C:\Users\65ran>adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

C:\Users\65ran>adb devices
List of devices attached
emulator-5554   device


C:\Users\65ran>adb connect 127.0.0.1:5554
unable to connect to 127.0.0.1:5554:5554

C:\Users\65ran>adb connect 127.0.0.1:5555
connected to 127.0.0.1:5555
C:\Users\65ran>python C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py
error: more than one device and emulator
Traceback (most recent call last):
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 41, in <module>
    main()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 34, in main
    cls = Screen()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 12, in __init__
    window_size = subprocess.check_output(['adb', 'shell', 'wm', 'size'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', 'shell', 'wm', 'size']' returned non-zero exit status 4294967295.

C:\Users\65ran>

**Comment by ranger65** [comment]
![Screenshot (83)](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/55602749/040ea0c1-1d43-4c9d-ad8b-c09eb0298a4c)

**Comment by TheAdroitDBA** [comment]
DO NOT run adb-start server. Run the following commands in order. 

adb kill-server
adb connect 127.0.0.1:5555

**Comment by ranger65** [comment]
I restarted my pc and did as told and I got the same result so I did devices and still says two?




Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\65ran>adb kill-server

C:\Users\65ran>adb connect 127.0.0.1:5555
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 127.0.0.1:5555

C:\Users\65ran>python C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py
error: more than one device and emulator
Traceback (most recent call last):
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 41, in <module>
    main()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 34, in main
    cls = Screen()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 12, in __init__
    window_size = subprocess.check_output(['adb', 'shell', 'wm', 'size'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', 'shell', 'wm', 'size']' returned non-zero exit status 4294967295.

C:\Users\65ran>adb devices
List of devices attached
emulator-5554   device
127.0.0.1:5555  device


C:\Users\65ran>

**Comment by TheAdroitDBA** [comment]
The problem you are having is that the emulator-5554 device is attached as well. This is what mine looks like. I got that error every time I started the adb server.
This is the end state you are looking for
"List of devices attached
127.0.0.1:5555  device"

You could try: rebooting starting up bluestacks and verifying the port is still right. Then run

adb devices
it should show no devices at this point
then run
adb connect 127.0.0.1:5555
Aside from that I don't know why it would keep auto-connecting to your emulator every time you connect via port number.

**Comment by ranger65** [comment]
I throw in the towel just list it as a bug, even when I narrow it to one its because I turned debug off and on and it hasnt had time to catch up.  gg

**Comment by TheAdroitDBA** [comment]
One more attempt? I fought with it again this afternoon and I think I have a solid solution.

Close bluestacks

adb kill-server
adb start-server

adb devices 
(none should be there because bluestacks is closed)
start bluestacks
adb connect 127.0.0.1:5555

adb devices
(should only list 127.0.0.1:5555)

Test the screenshot script.

**Comment by ranger65** [comment]
done in order after pc restart and altho it changed the error there is still an error

**Comment by ranger65** [comment]
Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\65ran>adb kill-server

C:\Users\65ran>adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

C:\Users\65ran>adb devices
List of devices attached


C:\Users\65ran>adb connect 127.0.0.1:5555
connected to 127.0.0.1:5555

C:\Users\65ran>adb devices
List of devices attached
127.0.0.1:5555  offline


C:\Users\65ran>adb devices
List of devices attached
127.0.0.1:5555  device


C:\Users\65ran>python C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py
Traceback (most recent call last):
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 41, in <module>
    main()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 35, in main
    screenshot = cls.take_screenshot()
  File "C:\Users\65ran\AppData\Local\Programs\Python\Python38\Lib\site-packages\clashroyalebuildabot\screen.py", line 27, in take_screenshot
    screenshot_bytes = subprocess.run(['adb', 'exec-out', 'screencap'], check=True, capture_output=True).stdout
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', 'exec-out', 'screencap']' returned non-zero exit status 1.

C:\Users\65ran>
