### ISSUE TITLE
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9

### ISSUE THREAD

**Issue by carlos-dubon** [Pbatch/ClashRoyaleBuildABot#93]
I get the following error when running `main.py`:
```
Traceback (most recent call last):
  File "C:\Users\carlos\Documents\code\cr_bot\example\main.py", line 18, in <module>
    main()
  File "C:\Users\carlos\Documents\code\cr_bot\example\main.py", line 12, in main
    bot = CustomBot(card_names, debug=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlos\Documents\code\cr_bot\example\custom_bot.py", line 19, in __init__
    super().__init__(card_names, CustomAction, debug=debug)
  File "C:\Users\carlos\AppData\Local\Programs\Python\Python311\Lib\site-packages\clashroyalebuildabot\bot\bot.py", line 46, in __init__
    self.detector = Detector(card_names, debug=self.debug)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlos\AppData\Local\Programs\Python\Python311\Lib\site-packages\clashroyalebuildabot\state\detector.py", line 29, in __init__
    self.number_detector = NumberDetector(os.path.join(DATA_DIR, 'number.onnx'))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlos\AppData\Local\Programs\Python\Python311\Lib\site-packages\clashroyalebuildabot\state\onnx_detector.py", line 9, in __init__
    self.sess = onnxruntime.InferenceSession(self.model_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carlos\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "C:\Users\carlos\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\carlos\AppData\Local\Programs\Python\Python311\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```

**Comment by Pbatch** [comment]
@all-contributors please add @carlos-dubon for a bug report
