### ISSUE TITLE
Error in example.py

### ISSUE THREAD

**Issue by IIgorrrrr** [Pbatch/ClashRoyaleBuildABot#95]
Custom Bot is now running...
Traceback (most recent call last):
  File "C:\Users\Iiro Hei\Downloads\ClashRoyaleBuildABot\example\main.py", line 18, in <module>
    main()
  File "C:\Users\Iiro Hei\Downloads\ClashRoyaleBuildABot\example\main.py", line 14, in main
    bot.run()
  File "C:\Users\Iiro Hei\Downloads\ClashRoyaleBuildABot\example\custom_bot.py", line 42, in run
    self.set_state()
  File "C:\Users\Iiro Hei\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 116, in set_state
    self.state = self.detector.run(screenshot)
  File "C:\Users\Iiro Hei\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\detector.py", line 63, in run
    self._draw_text(d, v['bounding_box'], str(v['number']))
  File "C:\Users\Iiro Hei\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\state\detector.py", line 35, in _draw_text
    text_width, text_height = self.font.getsize(text)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**Comment by KingJulian4152** [comment]
I have the same problem as well

**Comment by Pbatch** [comment]
@all-contributors-bot please thank @llgorrrrr for reporting a bug

**Comment by Pbatch** [comment]
@all-contributors-bot please thank @llgorrrrr for reporting a bug

**Comment by Pbatch** [comment]
@all-contributors please thank @IIgorrrrr for reporting a bug

**Comment by Pbatch** [comment]
@all-contributors please thank @IIgorrrrr for a bug report

**Comment by IIgorrrrr** [comment]
Didn't work :(

**Comment by nschnap** [comment]
Didnt work, please reopen this issue
